config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  devise_for :users do
   delete '/users/sign_out' => 'devise/sessions#destroy'
=======
  default_url_options :host => "localhost:3000"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    devise_for :users do
      delete '/users/sign_out' => 'devise/sessions#destroy'
      end
      root "messages#index"
      
        resources :messages do 
          delete  '/messages/:id' => 'messages#destroy'
          resources :comments do 
          end
        end
      resources :posts do
        resources :likes
        resources :messages
      end
>>>>>>> 5b376bc... commit for the reposertry
  end
  root "messages#index"
  resources :messages do 
    delete  '/messages/:id' => 'messages#destroy'
    resources :comments
    
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
  has_many :likes,dependent: :destroy
  # validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post


end

app/models/message.rb
class Message < ApplicationRecord
<<<<<<< HEAD
    belongs_to :user 
    has_many :comments , dependent: :destroy
end
=======
 self.table_name = :messages
    belongs_to :user , dependent: :destroy
    has_many :comments, dependent: :destroy
    belongs_to :post, inverse_of: :message

    # accepts_nested_attributes_for :posts
end
>>>>>>> 5b376bc... commit for the reposertry

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, AttachmentUploader # Tells rails to use this uploader for this model.   
    mount_uploader :video, VideoUploader # Tells rails to use this uploader for this model.   
    # has_one_attached :video_ss    # has_many :messages,dependent: :destroy
    has_many :user 
    has_many :likes, dependent: :destroy

    # validates :image, presence: true

    # accepts_nested_attributes_for :messages
end

app/models/user.rb
class User < ApplicationRecord
<<<<<<< HEAD
  has_many :messages , dependent: :destroy
  has_many :comments , dependent: :destroy

=======
  has_many :messages, dependent: :destroy 
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :posts , dependent: :destroy
>>>>>>> 5b376bc... commit for the reposertry
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :find_message
    before_action :find_comment, only: [:edit,:update,:destroy]
 before_action :authenticate_user!
    def create

        @comment = @message.comments.create(comment_params)
        @comment.user_id = current_user.id
        
        if @comment.save
            redirect_to message_path(@message)
        else
            render "new"
        end
    end
   
    def edit
    end
    def update
        if @comment.update(comment_params)
            redirect_to message_path(@message)
        else
            render 'edit'
        end
    end
    def destroy
        @comment.destroy
        redirect_to message_path(@message)
    end
    private

    def comment_params
    params.require(:comment).permit(:content)
    end

    def find_message
        @message = Message.find(params[:message_id])
    end
    def find_comment
        @comment = @message.comments.find(params[:id])
               
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_post
    before_action :find_like,only: [:destroy]
    before_action :authenticate_user!
 
    def create
        if already_liked?
        flash[:notice] = "You can't like more than once"
        else
        @post.likes.create(user_id: current_user.id)
        end
        redirect_to  @post
    end
    
    # def show
    #  @post = @message.Comment.find_by(params[:id])

    # end
    def destroy
        if already_liked?
            @like.destroy
        end
        redirect_to @post
    end

    private 
    def find_post
     @post = Post.find(params[:post_id])
    end

    def already_liked?
      Like.where(user_id: current_user.id,post_id: params[:post_id]).exists?        
    end
    def find_like
        @like = @post.likes.find(params[:id])
    end 
end

app/controllers/messages_controller.rb
    class MessagesController < ApplicationController
    before_action :find_message, only: [:show,:edit,:update,:destroy]
    before_action :authenticate_user! , except: [:index,:show] 
        def index
         @message = Message.all
        end

        def new
            @message = current_user.messages.build
        end

        def create
            @message =current_user.messages.build(message_params)
            if @message.save
            redirect_to root_path
            else
            render :new
            end
        end
        def show
        end

        def update
            if @message.update(message_params)
                redirect_to message_path(@message)
            else
                render :edit
            end
        end
        def edit
        end
        def destroy
            @message.destroy
            redirect_to "/"
        end
        private 
        
        def message_params
            params.require(:message).permit(:title,:description,:user_id)
        end
        def find_message
            @message = Message.find(params[:id])
        end
    end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_post, only:[:show, :destroy, :edit]
    # before_action :find_message, only:[:new]

    def index
        @posts = Post.all 
    end
    
    def new
        @post = Post.new
        # @messages.post.build
    end
    
    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        if @post.save
         redirect_to "http://localhost:3000/posts", notice: "Successfully uploaded."  
       else
         render :new
       end
    end
    
    def show
        @post = Post.find(params[:id])

    end
     def destroy
     @post.destroy
     redirect_to "http://localhost:3000/posts"
     end

    private
    def post_params
     params.require(:post).permit(:image,:video_ss)
    end

    def find_post
        @post = Post.find(params[:id])
    end
    # def find_message
    #     @message = Message.find_by(params[:id])
    # end
end

app/controllers/posts_to_messages_controller.rb
class PostsController < MessagesController
  
    

  
end

app/controllers/text.rb
!/usr/bin/ruby

 
$global_variable = 10
class Employee
         
    def print_global
        puts "Global variable in Employee class is #$global_variable"
    end
    def initialize(id, name, age)
        # Instance Variables     
        @Emp_id = id
        @Emp_name = name
        @Emp_age = age
    end

        # displaying result
    def display_details()
    
        puts "The Employee id is  #@Emp_id"
        puts "The Employee name is #@Emp_name"
        puts "The Employee age is  #@Emp_age"    
    end

end

class Two2
 def print_global
 puts "Global variable in two2 class is #$global_variable"
 end
end
Employeeobj = Employee.new("11", "Ram", 21);
Employeeobj.print_global
Employeeobj.display_details()

Two2obj = Two2.new
Two2obj.print_global
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<br>
<p><%= comment.content %></p>
<p>Posted By : <%=comment.user.email %> <%=time_ago_in_words(comment.created_at)%>ago</p>

<<<<<<< HEAD

<% if user_signed_in? %>
    <% if @message.user_id == current_user.id %>
        <%= link_to "Edit", edit_message_comment_path(comment.message , comment) %>
        <%= button_to "Delete", message_comment_path(comment.message , comment), method: :delete , data: {confirm: "Are you sure?"} %>
    <% end %>
<% end %>
=======
    <% if user_signed_in? %>
        <% if @message.user_id == current_user.id %>
        <%# <%= link_to 'like',message_comment_like_path(@message,comment.message)%> 
            <%= link_to "Edit", edit_message_comment_path(comment.message , comment) %>
            <%= button_to "Delete", message_comment_path(comment.message , comment), method: :delete , data: {confirm: "Are you sure?"} %>
        <% end %>
    <% end %>
    <%# <%= comment.likes.count  %>
    <%# # <%= (comment.message.likes.count) == 1 ? 'like' 'likes' %>
>>>>>>> 5b376bc... commit for the reposertry

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
<<<<<<< HEAD

<div>
  <%= f.input :content, label: "Comment" %>
</div>
<div><%= f.button :submit %></div>

=======
  <div>
    <%= f.input :content, label: "Comment" %>
  </div>
  <div><%= f.button :submit %></div>
 
>>>>>>> 5b376bc... commit for the reposertry
<% end %>

app/views/comments/edit.html.erb
<h2>Edit Page</h2>

<%= simple_form_for ([@message,@comment]) do |f| %>

<%= f.input :content, label: "Comment" %>

<%= f.button :submit %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <%= link_to "Message Board",root_path, class:"navbar-brand", style: "color: white; text-decoration:none;" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Sign Up",new_user_registration_path,class:"nav-link active ",style:"color: white; margin-top:16px; margin-right: 12px ; text-decoration:none; " %>
       </li>
       <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Sign Out",destroy_user_session_path,method: :delete, class:"nav-link active ",style:"color:white; margin-top:16px; text-decoration:none; "%>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Log In",  new_user_session_path ,class:"nav-link active",style:"color:white; margin-top:16px; text-decoration:none;" %>
      </li>
      <% end %>
      </ul>
      <% if user_signed_in? %>
<<<<<<< HEAD
     <p><%= link_to "New Message", new_message_path,class:"navbar_right navbar-text navbar-link" %></p>
=======
     <p><%= link_to "New Message", new_message_path,class:"navbar-right navbar-text navbar-link btn btn-primary", style:"color: white;text-decoration:none; "%></p><br>
     <p><%= link_to "New Post", new_post_path,class:"navbar-right navbar-text navbar-link btn btn-primary", style:"color: white; margin-top:-14px; margin-right:16px;text-decoration:none; "%></p>

>>>>>>> 5b376bc... commit for the reposertry
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

   
    <%= render "layouts/header"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class = "container">
    <%= yield %>
    </div>
    
  </body>
</html>

app/views/likes/new.html.erb
<%= render "form"%>

app/views/messages/_form.html.erb
<%= simple_form_for  @message do |form| %>

<div>
  <%= form.input :title, label: "Title" %>

</div>

<div>
   <%= form.input :description, label: "Descripation" %>

</div>
<br>
<div>
  <%= form.button :submit %>
</div>

<% end %>

app/views/messages/edit.html.erb
<h1>Edit</h1>

<%= render "form" %>

app/views/messages/index.html.erb
<h1>This is index file </h1>


<% @message.each do |form|%>

<<<<<<< HEAD
<b>Title: </b><%= form.title %><br>
<%# <b>Description:</b> <%= form.description %><br>
<%= link_to "View Message", message_path(form), class:"btn btn-primary" %><br>
<%# <%= link_to "edit", edit_message_path(form)%><br> 
<% end %>

<br>

=======
<div class = "col-md-4">
<div class = "message">
    <h2 class= "message-title"> <%= form.title %><br></h2>
    <%= link_to "View Message", message_path(form), class:"btn-custom", style:"text-decoration:none" %><br>
</div>
</div>

<% end %>
>>>>>>> 5b376bc... commit for the reposertry
<%# <%= link_to "New Message", new_message_path,class: %>

app/views/messages/new.html.erb
<h1>New Messages</h1>
<%= render "form"%>

app/views/messages/show.html.erb
<h2><%=@message.title %><br></h2>
<p>Posted By : <%=@message.user.email %> <%=time_ago_in_words(@message.created_at)%>ago</p>

<strong>Description:</strong> <%=@message.description %><br>

<<<<<<< HEAD
<br>
<h3>Comments</h3>
<%= render @message.comments%>

<h2>Reply To Messages: </h2>
<%= render "comments/form"%><br>
=======
    <br>
    <h3>Comments</h3>
    <%= render @message.comments%>
   
   <%= render "likes/form"%>
    <h2 class= "reply-to-msg">Reply To Messages: </h2>
    <%= render "comments/form"%><br>
    <div class= "link btn-group">
      <%= link_to "Back",root_path, class: "btn btn-default"%>
      <% if user_signed_in? %>
        <% if @message.user_id == current_user.id %>
          <%= link_to "Edit", edit_message_path(@message), class: "btn btn-default"%>
          <%= button_to "Delete",message_path(@message), method: :delete, data: { confirm:"Are you Sure?" }, class: "btn btn-default" %>
          <%= link_to "show", post_path(@message), class: "btn btn-default"%>
       
        <% end %>
      <% end %>
    </div>
>>>>>>> 5b376bc... commit for the reposertry

<%= link_to "Back",root_path%>
<% if user_signed_in? %>
    <% if @message.user_id == current_user.id %>
        <%= link_to "Edit", edit_message_path(@message) %>
        <%= button_to "Delete",message_path(@message), method: :delete, data: { confirm:"Are you Sure?" } %>
    <% end %>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |f| %>
<% if f.image_url.present? || f.video.present? %>
<%= image_tag f.image_url %>
<%= video_tag f.video_url %>
<% end %>


<%# <%= button_to 'Like', post_likes_path(@post), method: :post %> 
<p><%= f.likes.count %><%= (f.likes.count) == 1 ? 'Like' : 'Likes' %> </p>
<%= link_to "View Post" ,post_path(f)%>
<br>
<br>
<% end %><br>

app/views/posts/new.html.erb
<%# <%= render "form"%> %>

<%= form_with(model:@post, local: true) do |f| %>
 
 <div>
 <%= f.label :image %>
 <%= f.file_field :image %>
 </div>
 <br>
 <div>
 <%= f.label :video %>
 <%= f.file_field :video %>
 </div> 
 <br>
<div>
  <%= f.submit %>
</div>
<% end %>

app/views/posts/show.html.erb
<% if @post.image_url.present? %>

Image <%= image_tag @post.image_url %><br><br>
<%# <% if @post.video.present? %>
  Video <%= video_tag @post.video_url.to_s, controls: true %> 
<%# <% end %> 
<%end%>



<p><%= @post.likes.count %><%= ( @post.likes.count) == 1 ? ' Like' : ' Likes' %> </p>
<% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
<% else %>
  <%= button_to 'Like', post_likes_path(@post), method: :post %>
<% end %>

<br>
<%= button_to "Delete",post_path(@post), method: :delete ,class: "btn btn-default" %>

<%= link_to "back",posts_path ,class: "btn btn-default" %>